package com.oli.projectsai.features.memory

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch

@Composable
fun AddToMemoryDialog(
    conversationText: String,
    modelLoaded: Boolean,
    autoSummarise: suspend (String) -> String,
    onSave: (String) -> Unit,
    onDismiss: () -> Unit
) {
    var summary by remember { mutableStateOf("") }
    var isGenerating by remember { mutableStateOf(false) }
    var hasGenerated by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    val scope = rememberCoroutineScope()

    AlertDialog(
        onDismissRequest = { if (!isGenerating) onDismiss() },
        title = { Text("Add to Memory") },
        text = {
            Column(
                modifier = Modifier.verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                if (!hasGenerated) {
                    Text(
                        "Let the loaded model extract key facts from this conversation, or write your own notes.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Button(
                        onClick = {
                            errorMessage = null
                            isGenerating = true
                            scope.launch {
                                try {
                                    summary = autoSummarise(conversationText)
                                    hasGenerated = true
                                } catch (t: Throwable) {
                                    errorMessage = t.message ?: "Summarisation failed"
                                } finally {
                                    isGenerating = false
                                }
                            }
                        },
                        modifier = Modifier.fillMaxWidth(),
                        enabled = !isGenerating && modelLoaded
                    ) {
                        if (isGenerating) {
                            CircularProgressIndicator(
                                modifier = Modifier.size(16.dp),
                                strokeWidth = 2.dp
                            )
                            Spacer(Modifier.width(8.dp))
                            Text("Summarising…")
                        } else {
                            Icon(Icons.Default.AutoAwesome, null, modifier = Modifier.size(18.dp))
                            Spacer(Modifier.width(8.dp))
                            Text("Auto-summarise")
                        }
                    }
                    if (!modelLoaded) {
                        Text(
                            "Load a model first to use auto-summarise.",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    errorMessage?.let {
                        Text(
                            it,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.error
                        )
                    }
                    HorizontalDivider()
                    Text("Or write your own:", style = MaterialTheme.typography.labelSmall)
                }

                OutlinedTextField(
                    value = summary,
                    onValueChange = { summary = it },
                    label = { Text("Memory notes") },
                    minLines = 5,
                    modifier = Modifier.fillMaxWidth(),
                    enabled = !isGenerating
                )

                if (hasGenerated) {
                    Text(
                        "Edit the summary above before saving. You can add, remove, or modify any line.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        },
        confirmButton = {
            TextButton(
                onClick = { onSave(summary.trim()) },
                enabled = summary.isNotBlank() && !isGenerating
            ) { Text("Save to Memory") }
        },
        dismissButton = {
            TextButton(onClick = onDismiss, enabled = !isGenerating) { Text("Cancel") }
        }
    )
}
