// AUTO-GENERATED by server/scripts/gen_ts_types.py — DO NOT EDIT.
// Re-run with `npm run gen-types` (from server/web/) after touching Pydantic models.

export interface ProjectItem {
  remote_id?: string | null;
  name: string;
  description?: string;
  manual_context?: string;
  accumulated_memory?: string;
  pinned_memories?: string;
  preferred_backend?: string;
  memory_token_limit?: number;
  context_length?: number;
  is_secret?: boolean;
  created_at: number;
  updated_at: number;
  deleted_at?: number | null;
}

export interface ChatItem {
  remote_id?: string | null;
  project_remote_id: string;
  title?: string;
  web_search_enabled?: boolean;
  created_at: number;
  updated_at: number;
  deleted_at?: number | null;
}

export interface MessageItem {
  remote_id?: string | null;
  chat_remote_id: string;
  role: string;
  content: string;
  token_count?: number;
  attachment_paths?: string;
  created_at: number;
  updated_at: number;
  deleted_at?: number | null;
}

export interface QuickActionItem {
  remote_id?: string | null;
  project_remote_id: string;
  name: string;
  prompt_template: string;
  sort_order?: number;
  created_at: number;
  updated_at: number;
  deleted_at?: number | null;
}

export interface PushBody {
  items: unknown[];
}

export interface GlobalContext {
  user_name?: string;
  rules?: string;
  updated_at?: number;
}

export interface InferenceMessage {
  role: string;
  content: string;
  images?: string[];
}

export interface InferenceConfig {
  model?: string;
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  apply_default_preamble?: boolean;
  num_ctx?: number | null;
}

export interface InferenceRequest {
  system_prompt?: string;
  messages: InferenceMessage[];
  config?: InferenceConfig;
  user_name?: string | null;
  global_rules?: string | null;
}

