"""
Generate TypeScript type declarations from the server's Pydantic models.

Single source of truth: any model the web client wants to consume is declared
once on the server and surfaced to the frontend through this generator. Run
after touching the Pydantic models so the web bundle stays in sync.

Usage (from repo root):

    python server/scripts/gen_ts_types.py > server/web/src/api/types.gen.ts

Or, if you don't have Python 3.10+ locally, via the project's docker image:

    docker run --rm -v "$PWD/server:/app" -w /app python:3.12-slim \\
        sh -c "pip install -q pydantic==2.10.3 fastapi==0.115.6 httpx==0.27.2 aiosqlite==0.20.0 && python scripts/gen_ts_types.py" \\
        > server/web/src/api/types.gen.ts

Hand-rolled emitter — small enough to maintain inline; avoids the heavyweight
`datamodel-code-generator` dependency.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# Allow `from routers.sync import ProjectItem` etc. when run from server/ or repo root.
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

from routers.sync import (  # noqa: E402
    ChatItem,
    GlobalContext,
    MessageItem,
    ProjectItem,
    PushBody,
    QuickActionItem,
)
from routers.inference import (  # noqa: E402
    InferenceConfig,
    InferenceMessage,
    InferenceRequest,
)


# Order matters: we emit interfaces top-down so the file reads naturally and
# any submodel referenced via $ref appears before its consumer.
MODELS = [
    ProjectItem,
    ChatItem,
    MessageItem,
    QuickActionItem,
    PushBody,
    GlobalContext,
    InferenceMessage,
    InferenceConfig,
    InferenceRequest,
]


def _ts_type(schema: dict[str, Any]) -> str:
    """Map a JSON-Schema fragment to a TypeScript type expression."""
    if "$ref" in schema:
        # "#/$defs/Foo" → "Foo"
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_ts_type(s) for s in schema["anyOf"])
    t = schema.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = schema.get("items", {})
        return f"{_ts_type(items)}[]"
    if t == "object":
        # Inline object — best-effort. We don't expect this in our schemas
        # since models are always factored out into their own classes.
        return "Record<string, unknown>"
    return "unknown"


def _emit_interface(name: str, schema: dict[str, Any]) -> str:
    out = [f"export interface {name} {{"]
    properties = schema.get("properties", {}) or {}
    required = set(schema.get("required") or [])
    for prop_name, prop_schema in properties.items():
        # A property with a default value isn't "required" from the API's POV
        # even if Pydantic typed it as non-Optional — clients can omit it.
        is_required = prop_name in required and "default" not in prop_schema
        suffix = "" if is_required else "?"
        out.append(f"  {prop_name}{suffix}: {_ts_type(prop_schema)};")
    out.append("}")
    return "\n".join(out)


def gen() -> str:
    parts: list[str] = [
        "// AUTO-GENERATED by server/scripts/gen_ts_types.py — DO NOT EDIT.",
        "// Re-run with `npm run gen-types` (from server/web/) after touching Pydantic models.",
        "",
    ]
    seen_defs: set[str] = set()
    interfaces: list[str] = []
    for cls in MODELS:
        schema = cls.model_json_schema()
        # Pull out $defs (referenced submodels) before emitting the top-level model.
        for def_name, def_schema in (schema.get("$defs") or {}).items():
            if def_name not in seen_defs:
                seen_defs.add(def_name)
                interfaces.append(_emit_interface(def_name, def_schema))
        if cls.__name__ not in seen_defs:
            seen_defs.add(cls.__name__)
            interfaces.append(_emit_interface(cls.__name__, schema))
    parts.append("\n\n".join(interfaces))
    parts.append("")
    return "\n".join(parts)


if __name__ == "__main__":
    print(gen())
