package com.oli.cortex.ui.memory

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.oli.cortex.inference.InferenceManager

@Composable
fun AddToMemoryDialog(
    conversationText: String,
    inferenceManager: InferenceManager?,
    onSave: (String) -> Unit,
    onDismiss: () -> Unit
) {
    var summary by remember { mutableStateOf("") }
    var isGenerating by remember { mutableStateOf(false) }
    var hasGenerated by remember { mutableStateOf(false) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Add to Memory") },
        text = {
            Column(
                modifier = Modifier.verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                if (!hasGenerated) {
                    Text(
                        "Generate a summary of this conversation to save to project memory, or write your own notes.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Button(
                        onClick = {
                            // In a real flow this would call the model to summarise.
                            // For now, provide a placeholder the user can edit.
                            isGenerating = true
                            summary = buildSummaryPlaceholder(conversationText)
                            isGenerating = false
                            hasGenerated = true
                        },
                        modifier = Modifier.fillMaxWidth(),
                        enabled = !isGenerating
                    ) {
                        Icon(Icons.Default.AutoAwesome, null, modifier = Modifier.size(18.dp))
                        Spacer(Modifier.width(8.dp))
                        Text(if (isGenerating) "Generating..." else "Auto-summarise")
                    }
                    HorizontalDivider()
                    Text("Or write your own:", style = MaterialTheme.typography.labelSmall)
                }

                OutlinedTextField(
                    value = summary,
                    onValueChange = { summary = it },
                    label = { Text("Memory notes") },
                    minLines = 5,
                    modifier = Modifier.fillMaxWidth()
                )

                if (hasGenerated) {
                    Text(
                        "Edit the summary above before saving. You can add, remove, or modify any line.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        },
        confirmButton = {
            TextButton(
                onClick = { onSave(summary.trim()) },
                enabled = summary.isNotBlank()
            ) { Text("Save to Memory") }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("Cancel") }
        }
    )
}

private fun buildSummaryPlaceholder(conversation: String): String {
    // This is a placeholder. In the full implementation, this would send
    // the conversation to the model with a condensation prompt.
    // For now, extract key lines as a starting point for the user to edit.
    val lines = conversation.lines().filter { it.isNotBlank() }
    return if (lines.size <= 5) {
        lines.joinToString("\n") { "- ${it.take(120)}" }
    } else {
        lines.take(3).joinToString("\n") { "- ${it.take(120)}" } +
            "\n- [Edit: add key decisions, updates, and facts from this conversation]"
    }
}
